"""Build a pruned, signed connectome graph from the public MaleCNS v1.0 bulk files.

No neuPrint account or API token is required. These files are public and CC-BY:
  gs://flyem-male-cns/v1.0/connectome-data/flat-connectome/

Inputs (downloaded, never committed):
  connectome-weights-male-cns-v1.0-minconf-0.5.feather   1.1 GB, full connection graph
  body-annotations-male-cns-v1.0-minconf-0.5.feather      13 MB, classes/types/sides
  body-neurotransmitters-male-cns-v1.0.feather            42 MB, per-neuron NT predictions

Outputs (committed):
  data/connectome/neurons.parquet
  data/connectome/edges.parquet
  data/connectome/manifest.json
  data/connectome/SCHEMA.md

Column names in the source files are auto-detected. If detection fails we abort and
print the real column names rather than guessing and building a wrong graph.
"""
from __future__ import annotations

import hashlib
import json
import sys
import tempfile
from pathlib import Path

import pandas as pd
import pyarrow.feather as feather
import requests
import yaml

BASE = "https://storage.googleapis.com/flyem-male-cns/v1.0/connectome-data/flat-connectome"
FILES = {
    "weights": "connectome-weights-male-cns-v1.0-minconf-0.5.feather",
    "annotations": "body-annotations-male-cns-v1.0-minconf-0.5.feather",
    "neurotransmitters": "body-neurotransmitters-male-cns-v1.0.feather",
}
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "connectome"

CANDIDATES = {
    "pre": ["body_pre", "bodyid_pre", "pre", "body_id_pre", "bodypre", "pre_body"],
    "post": ["body_post", "bodyid_post", "post", "body_id_post", "bodypost", "post_body"],
    "weight": ["weight", "count", "syn_count", "synapses", "n"],
    "body": ["bodyid", "body", "body_id"],
    "type": ["type", "cell_type", "celltype"],
    "class": ["class", "superclass", "cell_class"],
    "side": ["side", "soma_side"],
    "nt": ["consensus_nt", "top_nt", "predicted_nt", "nt", "neurotransmitter"],
}


def pick(columns, key, required=True, context=""):
    lower = {c.lower(): c for c in columns}
    for cand in CANDIDATES[key]:
        if cand in lower:
            return lower[cand]
    if required:
        sys.exit(
            f"FATAL: could not find a '{key}' column in {context}.\n"
            f"Columns present: {list(columns)}\n"
            f"Add the right name to CANDIDATES['{key}'] in src/build_connectome.py."
        )
    return None


def download(name: str, dest: Path) -> str:
    url = f"{BASE}/{name}"
    print(f"downloading {url}")
    sha = hashlib.sha256()
    with requests.get(url, stream=True, timeout=600) as r:
        r.raise_for_status()
        with dest.open("wb") as fh:
            for chunk in r.iter_content(chunk_size=8 << 20):
                fh.write(chunk)
                sha.update(chunk)
    mb = dest.stat().st_size / 1e6
    print(f"  {mb:,.0f} MB  sha256={sha.hexdigest()[:16]}")
    return sha.hexdigest()


def main() -> None:
    cfg = yaml.safe_load((ROOT / "config.yml").read_text())["connectome"]
    OUT.mkdir(parents=True, exist_ok=True)
    tmp = Path(tempfile.mkdtemp())
    shas = {}

    ann_path = tmp / FILES["annotations"]
    nt_path = tmp / FILES["neurotransmitters"]
    w_path = tmp / FILES["weights"]
    shas["annotations"] = download(FILES["annotations"], ann_path)
    shas["neurotransmitters"] = download(FILES["neurotransmitters"], nt_path)
    shas["weights"] = download(FILES["weights"], w_path)

    ann = feather.read_feather(ann_path)
    nt = feather.read_feather(nt_path)
    edges = feather.read_feather(w_path)

    schema = ["# Source file schemas", "", "Auto-generated by src/build_connectome.py.", ""]
    for label, df in (("annotations", ann), ("neurotransmitters", nt), ("weights", edges)):
        schema.append(f"## {FILES[label]}")
        schema.append(f"{len(df):,} rows")
        schema.append("")
        for col, dtype in df.dtypes.items():
            schema.append(f"- `{col}` ({dtype})")
        schema.append("")
    (OUT / "SCHEMA.md").write_text("\n".join(schema))
    print(f"wrote {OUT / 'SCHEMA.md'}")

    c_pre = pick(edges.columns, "pre", context="weights")
    c_post = pick(edges.columns, "post", context="weights")
    c_w = pick(edges.columns, "weight", context="weights")
    a_body = pick(ann.columns, "body", context="annotations")
    a_type = pick(ann.columns, "type", required=False)
    a_class = pick(ann.columns, "class", required=False)
    a_side = pick(ann.columns, "side", required=False)
    n_body = pick(nt.columns, "body", context="neurotransmitters")
    n_nt = pick(nt.columns, "nt", context="neurotransmitters")

    edges = edges[[c_pre, c_post, c_w]].rename(
        columns={c_pre: "pre", c_post: "post", c_w: "weight"}
    )
    n_edges_raw = len(edges)
    edges = edges[edges["weight"] >= cfg["min_synapses"]]
    print(f"edges: {n_edges_raw:,} -> {len(edges):,} at >= {cfg['min_synapses']} synapses")

    neurons = pd.DataFrame({"body": ann[a_body]})
    neurons["type"] = ann[a_type].astype("string") if a_type else pd.NA
    neurons["class"] = ann[a_class].astype("string") if a_class else pd.NA
    neurons["side"] = ann[a_side].astype("string") if a_side else pd.NA
    neurons = neurons.drop_duplicates("body")

    is_dn = pd.Series(False, index=neurons.index)
    if a_class:
        is_dn |= neurons["class"].str.lower().str.contains(
            cfg["readout_class_pattern"], na=False
        )
    if a_type:
        is_dn |= neurons["type"].str.upper().str.startswith(
            cfg["readout_type_prefix"], na=False
        )
    neurons["is_readout"] = is_dn
    readout = set(neurons.loc[is_dn, "body"])
    print(f"readout (descending) neurons: {len(readout):,}")
    if not readout:
        sys.exit("FATAL: no readout neurons found. Check readout_* patterns against SCHEMA.md.")

    annotated = set(neurons["body"])
    edges = edges[edges["pre"].isin(annotated) & edges["post"].isin(annotated)]

    keep = set(readout)
    frontier = set(readout)
    for hop in range(cfg["hops_upstream_of_readout"]):
        sel = edges[edges["post"].isin(frontier)]
        strength = sel.groupby("pre")["weight"].sum().sort_values(ascending=False)
        new = [b for b in strength.index if b not in keep]
        room = cfg["max_neurons"] - len(keep)
        if room <= 0:
            break
        new = new[:room]
        keep.update(new)
        frontier = set(new)
        print(f"hop {hop + 1}: +{len(new):,} neurons, total {len(keep):,}")
        if not new:
            break

    neurons = neurons[neurons["body"].isin(keep)].reset_index(drop=True)
    edges = edges[edges["pre"].isin(keep) & edges["post"].isin(keep)].reset_index(drop=True)

    nt_map = dict(zip(nt[n_body], nt[n_nt].astype("string").str.lower()))
    exc = set(cfg["excitatory"])
    inh = set(cfg["inhibitory"])
    pre_nt = edges["pre"].map(nt_map)
    sign = pre_nt.map(lambda v: 1 if v in exc else (-1 if v in inh else 0))
    n_unsigned = int((sign == 0).sum())
    edges["sign"] = sign
    edges = edges[edges["sign"] != 0].reset_index(drop=True)
    print(f"dropped {n_unsigned:,} edges with no usable neurotransmitter prediction")

    if len(edges) > cfg["max_edges"]:
        edges = edges.nlargest(cfg["max_edges"], "weight").reset_index(drop=True)
        print(f"capped to {len(edges):,} strongest edges")

    neurons["nt"] = neurons["body"].map(nt_map)
    neurons.to_parquet(OUT / "neurons.parquet", index=False)
    edges.to_parquet(OUT / "edges.parquet", index=False)

    manifest = {
        "dataset": cfg["dataset"],
        "license": "CC-BY",
        "attribution": "MaleCNS v1.0. HHMI Janelia (FlyEM), University of Cambridge, MRC LMB, Google Research.",
        "source_bucket": "gs://flyem-male-cns/v1.0/connectome-data/flat-connectome/",
        "source_sha256": shas,
        "params": cfg,
        "detected_columns": {
            "weights": {"pre": c_pre, "post": c_post, "weight": c_w},
            "annotations": {"body": a_body, "type": a_type, "class": a_class, "side": a_side},
            "neurotransmitters": {"body": n_body, "nt": n_nt},
        },
        "counts": {
            "edges_in_source": int(n_edges_raw),
            "neurons_kept": int(len(neurons)),
            "edges_kept": int(len(edges)),
            "readout_neurons": int(neurons["is_readout"].sum()),
            "edges_dropped_no_nt": n_unsigned,
            "excitatory_edges": int((edges["sign"] == 1).sum()),
            "inhibitory_edges": int((edges["sign"] == -1).sum()),
        },
    }
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2, default=str))

    for f in ("neurons.parquet", "edges.parquet"):
        mb = (OUT / f).stat().st_size / 1e6
        print(f"{f}: {mb:.1f} MB")
        if mb > 80:
            sys.exit(f"FATAL: {f} is {mb:.0f} MB, too big to commit. Lower max_neurons or max_edges.")

    print(f"\n{len(neurons):,} neurons, {len(edges):,} signed edges -> data/connectome/")


if __name__ == "__main__":
    main()
